### ISSUE TITLE
ubuntu 14.04 Install issue

### ISSUE THREAD

**Issue by kncshw** [scoofy/wxStocks#2]
Hi scoofy,

I got the following issue when installing:

Startup may take a few moments...
File: wxStocks_db_functions.py
Line 156: 

    Loading GLOBAL_STOCK_DICT: this may take a couple of minutes.If this is your first time opening wxStocks, please ignore the following exception, otherwise, your previously saved data may have been deleted.
File: wxStocks_db_functions.py
Line 166: [Errno 2] No such file or directory: 'wxStocks_data/all_stocks_dict.pk'

File: wxStocks_db_functions.py
Line 186: Loading GLOBAL_ATTRIBUTE_SET
If this is your first time opening wxStocks, please ignore the following exception, otherwise, your previously saved data may have been deleted.
File: wxStocks_db_functions.py
Line 194: [Errno 2] No such file or directory: 'wxStocks_data/all_attributes_set.pk'
File: wxStocks_db_functions.py
Line 54: Loading GLOBAL_TICKER_LIST
File: wxStocks_db_functions.py
Line 58: [Errno 2] No such file or directory: 'wxStocks_data/ticker.pk'
File: wxStocks_db_functions.py
Line 503: config.ENCRYPTION_POSSIBLE False
File: wxStocks_db_functions.py
Line 510: attempting to load 0 possible portfolios
File: wxStocks_db_functions.py
Line 207: Loading GLOBAL_STOCK_SCREEN_DICT
File: wxStocks_db_functions.py
Line 211: [Errno 2] No such file or directory: 'wxStocks_data/screen_dict.pk'
File: wxStocks_db_functions.py
Line 257: Loading SCREEN_NAME_AND_TIME_CREATED_TUPLE_LIST
File: wxStocks_db_functions.py
Line 261: [Errno 2] No such file or directory: 'wxStocks_data/screen_names_and_times_tuple_list.pk'
Traceback (most recent call last):
  File "wxStocks.py", line 92, in <module>
    main()
  File "wxStocks.py", line 90, in main
    gui.MainFrame().Show()
  File "/home/kaini/fintech/wxStocks/wxStocks_modules/wxStocks_gui.py", line 50, in __init__
    self.welcome_page = WelcomePage(self.notebook)
  File "/home/kaini/fintech/wxStocks/wxStocks_modules/wxStocks_gui.py", line 239, in __init__
    self.encryption_hardness_field.SetHint("default = 8")
AttributeError: 'TextCtrl' object has no attribute 'SetHint'

It appears that wx installed by ubuntu apt-get is not compatible.
Any known solution on Ubuntu/Debian?

**Comment by scoofy** [comment]
Interesting indeed. I've had it working fine on debian mint before and it works fine...

So... here's the thing... "Set Hint" is completely arbitrary. You can simply comment out any line that has a "Set Hint" function call. The are really just for show.

As far is fixing it for Ubuntu... I just got back from the bar, and i'm currently very busy with getting my apartment rented, but i could definitely get back to you about fixing it properly in like... i'd say June  5th or so... here are the docs for phoenix: https://wxpython.org/Phoenix/docs/html/wx.TextEntry.html#wx.TextEntry.SetHint

it's a really strange error, i'll definitely look into it later.

**Comment by scoofy** [comment]
Ahh... it looks like i may need to change that TextCtrl to a TextEntry

**Comment by kncshw** [comment]
Thank you for the quick comment! I will try to comment the line and let you know the outcome!

**Comment by scoofy** [comment]
With the new version, this should no longer be relevant. I've moved all the database stuff over to ZODB!!!
