### ISSUE TITLE
could you please add some test data(csv, xls) for us? thank you

### ISSUE THREAD

**Issue by royburns** [scoofy/wxStocks#3]
![image](https://user-images.githubusercontent.com/652375/45625108-b3545080-babe-11e8-98ee-f0b62652c997.png)
![image](https://user-images.githubusercontent.com/652375/45625144-c49d5d00-babe-11e8-8f32-751ea55e0a8a.png)

**Comment by scoofy** [comment]
Good catch, i'm back to working on this and i'll attempt to fix it today

**Comment by scoofy** [comment]
Okay, the newest push i just dropped should have a better CSV importer, and a sample default csv. Let me know what you think, i'll do XLS tomorrow maybe.

**Comment by scoofy** [comment]
Okay, sample portfolio imports are done for both XLS and CSV

**Comment by royburns** [comment]
thanks very much, i will try it after work 👍
