### ISSUE TITLE
logging.info in Gui Position Index

### ISSUE THREAD

**Issue by paulhoff** [scoofy/wxStocks#4]
Hi, thanks for putting this together.  Still figuring it out.  
When I ran this under windows I had to comment out lines 23 and 24 in wxStocks_gui_position_index.py:
    #if config.ENCRYPTION_POSSIBLE and (config.OS_TYPE_INDEX != 0): # if encryption and not on mac
    #    logging.info("FINISH THIS TEMPORARY RESTRUCTURING TO WORK CROSSPLATFORM")
because it threw an error about "logging" on my Windows machine:

> Traceback (most recent call last):
>   File "wxStocks.py", line 85, in <module>
>     main()
>   File "wxStocks.py", line 82, in main
>     import wxStocks_modules.wxStocks_gui as gui
>   File "D:\wxstocks\wxStocks_modules\wxStocks_gui.py", line 23, in <module>
>     from wxStocks_modules import wxStocks_gui_position_index as gui_position
>   File "D:\wxstocks\wxStocks_modules\wxStocks_gui_position_index.py", line 20, in <module>
>     class WelcomePage(object):
>   File "D:\wxstocks\wxStocks_modules\wxStocks_gui_position_index.py", line 24, in WelcomePage
>     logging.info("FINISH THIS TEMPORARY RESTRUCTURING TO WORK CROSSPLATFORM")
> NameError: name 'logging' is not defined

But then it seemed to work fine.

**Comment by scoofy** [comment]
Ha! Thanks for pointing that out, i need to import logging into the position module. I can do that now

**Comment by scoofy** [comment]
done

**Comment by scoofy** [comment]
It's a work in progress, i'm now modifying the xbrl importer in a separate library on my github page to be reintroduced as an independent module. Since yql died it's been a lot less useful, but if i can manage to get serious 10-K parsing working... watch out
